@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Wed Apr 29 21:08:48 +0100 2020
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto be981aa9f7874c46a10cdcbdb70ed88c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot cfg_tb_pwm_behav xil_defaultlib.cfg_tb_pwm -log elaborate.log"
call xelab  -wto be981aa9f7874c46a10cdcbdb70ed88c --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip -L xpm --snapshot cfg_tb_pwm_behav xil_defaultlib.cfg_tb_pwm -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
